name: Deploy to AWS Fargate

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=YOUR_ECR_REPO_NAME  # Replace with your ECR repository name
          TAG=$(echo $GITHUB_SHA | cut -c1-7)
          docker build -t $IMAGE_NAME:$TAG .
          docker tag $IMAGE_NAME:$TAG YOUR_AWS_ACCOUNT_ID.dkr.ecr.YOUR_REGION.amazonaws.com/$IMAGE_NAME:$TAG
          docker push YOUR_AWS_ACCOUNT_ID.dkr.ecr.YOUR_REGION.amazonaws.com/$IMAGE_NAME:$TAG

      - name: Terraform Setup
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve
        env:
          TF_VAR_image = "YOUR_AWS_ACCOUNT_ID.dkr.ecr.YOUR_REGION.amazonaws.com/YOUR_ECR_REPO_NAME:$TAG"  # Pass the image URI
